[package]
name = "ratatea"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.24"
ratatui = "0.20"
rusqlite = { version= "0.31.0", features = ["bundled"] }
serde_json = "1.0.134"
serde = { version = "1.0.217", features = ["derive"] }